### ISSUE TITLE
Change default endpoint in settup.json

### ISSUE THREAD

**Issue by aimerib** [kalebbroo/SwarmUI-MagicPromptExtension#2]
Thank you so much for this extension! The default `"LlmEndpoint": "http://192.168.0.15:11434"` field uses your specific network scheme, which can cause issues. I think the user is EXPECTED to change this, but in most cases, this should probably be `"LlmEndpoint": "http://localhost:11434"` since they won't be coming from a different machine on the network, and if they are, they are more likely to know this. Only reason why I'm raising this as an issue is that my expectation was that it would work out of the box with default setups:
* Running Swarm locally
* Running Ollama locally on the same machine
* Expected everything to be pointed to default ports on localhost

and in reality, my computer on the network had the ip of 192.168.0.108. This was simple to fix (updating the settings.json file), but it could be confusing to users.

**Comment by kalebbroo** [comment]
This is why it is explicitly started in the instructions you need to change that. However, This will be changed soon. My plan is for when the user first opens the tab it will prompt them to set the url and the LLM instructions or use the default. They will also be able to change it at any time directly in the UI.

**Comment by aimerib** [comment]
Since this request will be rendered moot in the next version, would you like me to close this? Or keep it open for a satisfying [#]closes <issue> commit?

**Comment by kalebbroo** [comment]
The fix has been pushed to master.
